export interface MethodSpec {
  name: string;
  category: string;
  description: string;
  parameters: string;
  returns: string;
  example: string;
  /** True if the method mutates database state. Omitted/false means read-only. */
  write?: boolean;
}

export const API_SPEC: MethodSpec[] = [
  // ── events ──
  {
    name: "api.events.list",
    category: "events",
    description: "List configured events (filtered to allowed event IDs)",
    parameters: "()",
    returns: "Event[]",
    example: "const events = await api.events.list(); return events;",
  },
  {
    name: "api.events.get",
    category: "events",
    description: "Get event details with host info",
    parameters: "(eventId: number)",
    returns: "Event & { host: Host }",
    example: "const event = await api.events.get(18); return event;",
  },
  {
    name: "api.events.getTests",
    category: "events",
    description: "Get all tests for an event (admin view, includes hidden)",
    parameters: "(eventId: number)",
    returns: "Test[]",
    example: "const tests = await api.events.getTests(18); return tests;",
  },
  {
    name: "api.events.getOrganizations",
    category: "events",
    description: "Get orgs registered for an event with coaches",
    parameters: "(eventId: number)",
    returns: "Array<OrgEvent & { org: Org & { coaches: OrgCoach[] } }>",
    example: "const orgs = await api.events.getOrganizations(18); return orgs;",
  },
  {
    name: "api.events.getTeams",
    category: "events",
    description: "Get all teams for an event",
    parameters: "(eventId: number)",
    returns: "Team[]",
    example: "const teams = await api.events.getTeams(18); return teams;",
  },
  {
    name: "api.events.getStudents",
    category: "events",
    description: "Get all students registered for an event",
    parameters: "(eventId: number)",
    returns: "StudentEvent[]",
    example: "const students = await api.events.getStudents(18); return students;",
  },
  {
    name: "api.events.getIndependentTeams",
    category: "events",
    description: "Get teams not in any organization",
    parameters: "(eventId: number)",
    returns: "Team[]",
    example: "const teams = await api.events.getIndependentTeams(18); return teams;",
  },
  {
    name: "api.events.getTicketCount",
    category: "events",
    description: "Get total tickets sold for an event",
    parameters: "(eventId: number)",
    returns: "number",
    example: "const count = await api.events.getTicketCount(18); return count;",
  },
  {
    name: "api.events.getCustomFields",
    category: "events",
    description: "Get custom fields for an event",
    parameters: '(eventId: number, table?: "orgs" | "students" | "teams")',
    returns: "CustomField[]",
    example: 'const fields = await api.events.getCustomFields(18, "students"); return fields;',
  },

  // ── students ──
  {
    name: "api.students.list",
    category: "students",
    description: "List students for an event with optional pagination",
    parameters: "(eventId: number, options?: { limit?: number; offset?: number; withDetails?: boolean })",
    returns: "StudentEvent[]",
    example: "const students = await api.students.list(18, { limit: 20 }); return students;",
  },
  {
    name: "api.students.get",
    category: "students",
    description: "Get student event details (team, org, waiver) by internal student_id (UUID). Prefer getByFrontId when you only have the user-facing front_id.",
    parameters: "(studentId: string, eventId: number)",
    returns: "StudentEvent | null",
    example: 'const se = await api.students.get("abc-123", 18); return se;',
  },
  {
    name: "api.students.getByFrontId",
    category: "students",
    description: "Resolve a student by their user-facing front_id (the ID shown on badges / given to users). This is the primary way to look up a student when the user references them by ID.",
    parameters: "(eventId: number, frontId: number)",
    returns: "StudentEvent | null",
    example: "const se = await api.students.getByFrontId(18, 142); return se;",
  },
  {
    name: "api.students.search",
    category: "students",
    description: "Search students by name, email, or front_id (user-facing ID).",
    parameters: "(params: { eventId: number; name?: string; email?: string; frontId?: number })",
    returns: "StudentEvent[]",
    example: 'const results = await api.students.search({ eventId: 18, name: "John" }); return results;',
  },
  {
    name: "api.students.getWithoutTeam",
    category: "students",
    description: "Get students not assigned to any team",
    parameters: "(eventId: number)",
    returns: "StudentEvent[]",
    example: "const unassigned = await api.students.getWithoutTeam(18); return unassigned;",
  },
  {
    name: "api.students.getTicketOrder",
    category: "students",
    description: "Get student's ticket order with refund status",
    parameters: "(studentId: string, eventId: number)",
    returns: "TicketOrder | null",
    example: 'const order = await api.students.getTicketOrder("abc-123", 18); return order;',
  },
  {
    name: "api.students.getAvailableTickets",
    category: "students",
    description: "Get net available tickets for a student",
    parameters: "(studentId: string, eventId: number)",
    returns: "number",
    example: 'const available = await api.students.getAvailableTickets("abc-123", 18); return available;',
  },
  {
    name: "api.students.transferToTeam",
    category: "students",
    description: "Move student to a team (use -1 to remove from team)",
    parameters: "(studentEventId: number, teamId: number)",
    returns: "StudentEvent",
    example: "const result = await api.students.transferToTeam(42, 7); return result;",
    write: true,
  },
  {
    name: "api.students.transferToOrg",
    category: "students",
    description: "Move student to an org (removes team, use -1 to remove org)",
    parameters: "(studentEventId: number, orgId: number)",
    returns: "StudentEvent",
    example: "const result = await api.students.transferToOrg(42, 5); return result;",
    write: true,
  },
  {
    name: "api.students.removeFromTeam",
    category: "students",
    description: "Remove student from team (keep event registration)",
    parameters: "(studentEventId: number)",
    returns: "StudentEvent",
    example: "const result = await api.students.removeFromTeam(42); return result;",
    write: true,
  },
  {
    name: "api.students.removeFromEvent",
    category: "students",
    description: "Delete student registration from event entirely",
    parameters: "(studentEventId: number)",
    returns: "{ success: boolean }",
    example: "const result = await api.students.removeFromEvent(42); return result;",
    write: true,
  },

  // ── teams ──
  {
    name: "api.teams.list",
    category: "teams",
    description: "List all teams for an event",
    parameters: "(eventId: number)",
    returns: "Team[]",
    example: "const teams = await api.teams.list(18); return teams;",
  },
  {
    name: "api.teams.get",
    category: "teams",
    description: "Get team details with members",
    parameters: "(teamId: number)",
    returns: "Team & { members: StudentEvent[] }",
    example: "const team = await api.teams.get(7); return team;",
  },
  {
    name: "api.teams.search",
    category: "teams",
    description: "Search teams by name, join code, or front_id (user-facing ID).",
    parameters: "(eventId: number, params: { name?: string; joinCode?: string; frontId?: number })",
    returns: "Team[]",
    example: 'const teams = await api.teams.search(18, { name: "Alpha" }); return teams;',
  },
  {
    name: "api.teams.getByFrontId",
    category: "teams",
    description: "Resolve a team by its user-facing front_id. Primary lookup when the user references a team by ID.",
    parameters: "(eventId: number, frontId: number)",
    returns: "(Team & { members: StudentEvent[] }) | null",
    example: "const team = await api.teams.getByFrontId(18, 31); return team;",
  },
  {
    name: "api.teams.getMembers",
    category: "teams",
    description: "Get team members",
    parameters: "(teamId: number)",
    returns: "StudentEvent[]",
    example: "const members = await api.teams.getMembers(7); return members;",
  },
  {
    name: "api.teams.getAvailableTickets",
    category: "teams",
    description: "Get team ticket pool (total - refunds) and used count",
    parameters: "(teamId: number, eventId: number)",
    returns: "{ pool: number; used: number }",
    example: "const tickets = await api.teams.getAvailableTickets(7, 18); return tickets;",
  },
  {
    name: "api.teams.transferToOrg",
    category: "teams",
    description: "Transfer team to organization (uses RPC, -1 to remove org)",
    parameters: "(teamId: number, orgId: number)",
    returns: "{ team: Team; students: StudentEvent[] }",
    example: "const result = await api.teams.transferToOrg(7, 5); return result;",
    write: true,
  },
  {
    name: "api.teams.create",
    category: "teams",
    description: "Create a new team for an event",
    parameters: "(eventId: number, teamData: { team_name?: string; org_id?: number })",
    returns: "Team",
    example: 'const team = await api.teams.create(18, { team_name: "Team Alpha" }); return team;',
    write: true,
  },
  {
    name: "api.teams.update",
    category: "teams",
    description: "Update team name",
    parameters: "(teamId: number, data: { team_name?: string })",
    returns: "Team",
    example: 'const team = await api.teams.update(7, { team_name: "New Name" }); return team;',
    write: true,
  },
  {
    name: "api.teams.delete",
    category: "teams",
    description: "Delete team (optionally delete students too)",
    parameters: "(teamId: number, deleteStudents?: boolean)",
    returns: "{ success: boolean; affectedStudents: number; deletedStudents: number }",
    example: "const result = await api.teams.delete(7); return result;",
    write: true,
  },

  // ── orgs ──
  {
    name: "api.orgs.list",
    category: "orgs",
    description: "List all orgs registered for an event with coaches",
    parameters: "(eventId: number)",
    returns: "Array<OrgEvent & { org: Org & { coaches: OrgCoach[] } }>",
    example: "const orgs = await api.orgs.list(18); return orgs;",
  },
  {
    name: "api.orgs.get",
    category: "orgs",
    description: "Get org details with coaches",
    parameters: "(orgId: number)",
    returns: "Org & { coaches: OrgCoach[] }",
    example: "const org = await api.orgs.get(5); return org;",
  },
  {
    name: "api.orgs.getDetails",
    category: "orgs",
    description: "Full org details: coaches, teams with members, event registration",
    parameters: "(orgId: number, eventId: number)",
    returns: "Org & { coaches, teams, orgEvent }",
    example: "const detail = await api.orgs.getDetails(5, 18); return detail;",
  },
  {
    name: "api.orgs.getTeams",
    category: "orgs",
    description: "Get org's teams with members for an event",
    parameters: "(orgId: number, eventId: number)",
    returns: "Array<Team & { members: StudentEvent[] }>",
    example: "const teams = await api.orgs.getTeams(5, 18); return teams;",
  },
  {
    name: "api.orgs.getTicketCount",
    category: "orgs",
    description: "Get net available tickets for an org (tickets - refunds)",
    parameters: "(eventId: number, orgId: number)",
    returns: "number",
    example: "const count = await api.orgs.getTicketCount(18, 5); return count;",
  },
  {
    name: "api.orgs.getTicketOrders",
    category: "orgs",
    description: "Get all ticket orders and refund requests for an org",
    parameters: "(orgId: number, eventId: number)",
    returns: "TicketOrder[]",
    example: "const orders = await api.orgs.getTicketOrders(5, 18); return orders;",
  },
  {
    name: "api.orgs.removeStudent",
    category: "orgs",
    description: "Remove student from org (clears org_id and team_id)",
    parameters: "(studentEventId: number)",
    returns: "StudentEvent",
    example: "const result = await api.orgs.removeStudent(42); return result;",
    write: true,
  },

  // ── tickets ──
  {
    name: "api.tickets.listOrders",
    category: "tickets",
    description: "List all ticket orders for an event",
    parameters: "(eventId: number)",
    returns: "TicketOrder[]",
    example: "const orders = await api.tickets.listOrders(18); return orders;",
  },
  {
    name: "api.tickets.getOrder",
    category: "tickets",
    description: "Get a specific ticket order with refund requests",
    parameters: "(ticketId: number)",
    returns: "TicketOrder",
    example: "const order = await api.tickets.getOrder(42); return order;",
  },
  {
    name: "api.tickets.listRefundRequests",
    category: "tickets",
    description: "List refund requests for an event, optionally filtered by status",
    parameters: '(eventId: number, status?: "PENDING" | "APPROVED" | "DENIED")',
    returns: "RefundRequest[]",
    example: 'const pending = await api.tickets.listRefundRequests(18, "PENDING"); return pending;',
  },
  {
    name: "api.tickets.getRefundRequest",
    category: "tickets",
    description: "Get a specific refund request with ticket details",
    parameters: "(refundId: number)",
    returns: "RefundRequest & { ticket: TicketOrder }",
    example: "const refund = await api.tickets.getRefundRequest(10); return refund;",
  },
  {
    name: "api.tickets.approveRefund",
    category: "tickets",
    description: "Approve a pending refund in the database. WARNING: This does NOT process the actual payment refund. The admin must still manually refund via Stripe/Eventbrite/Humanitix dashboard. Always inform the user of this when reporting the result.",
    parameters: "(refundId: number, quantity: number, responseMessage?: string)",
    returns: "RefundRequest & { _warning: string }",
    example: 'const result = await api.tickets.approveRefund(10, 2, "Approved"); return result;',
    write: true,
  },
  {
    name: "api.tickets.denyRefund",
    category: "tickets",
    description: "Deny a pending refund request",
    parameters: "(refundId: number, responseMessage?: string)",
    returns: "RefundRequest",
    example: 'const result = await api.tickets.denyRefund(10, "Event is non-refundable"); return result;',
    write: true,
  },
  {
    name: "api.tickets.getEventRevenue",
    category: "tickets",
    description: "Calculate total revenue: gross, refunded, net",
    parameters: "(eventId: number)",
    returns: "{ ticketPriceCents, totalSold, totalRefunded, netTickets, grossRevenueCents, refundedCents, netRevenueCents }",
    example: "const revenue = await api.tickets.getEventRevenue(18); return revenue;",
  },

  // ── tests ──
  {
    name: "api.tests.list",
    category: "tests",
    description: "List all tests for an event",
    parameters: "(eventId: number)",
    returns: "Test[]",
    example: "const tests = await api.tests.list(18); return tests;",
  },
  {
    name: "api.tests.get",
    category: "tests",
    description: "Get test details (from detailed view)",
    parameters: "(testId: number)",
    returns: "Test (detailed)",
    example: "const test = await api.tests.get(5); return test;",
  },
  {
    name: "api.tests.getProblems",
    category: "tests",
    description: "Get test problems ordered by problem number",
    parameters: "(testId: number)",
    returns: "TestProblem[]",
    example: "const problems = await api.tests.getProblems(5); return problems;",
  },
  {
    name: "api.tests.getTestTakers",
    category: "tests",
    description: "Get test takers with details (enriched with front_id for individuals)",
    parameters: "(testId: number)",
    returns: "TestTaker[]",
    example: "const takers = await api.tests.getTestTakers(5); return takers;",
  },
  {
    name: "api.tests.getResults",
    category: "tests",
    description: "Get graded test answers",
    parameters: "(testId: number)",
    returns: "GradedTestAnswer[]",
    example: "const results = await api.tests.getResults(5); return results;",
  },
  {
    name: "api.tests.getScanGradeStats",
    category: "tests",
    description: "Get scan grading progress: total, graded, conflicts",
    parameters: "(testId: number)",
    returns: "{ totalProblems: number; gradedProblems: number; conflictProblems: number }",
    example: "const stats = await api.tests.getScanGradeStats(5); return stats;",
  },
  {
    name: "api.tests.getLeaderboard",
    category: "tests",
    description: "Unified scoreboard. Sums points from ALL three sources — graded_test_answers (online), scan_grades (in-person paper), manual_grades (Guts/team) — so it works for any test mode, including hybrids. Every row has front_id + display_name (use those, not internal IDs). scoreBreakdown shows the per-source split. Sorted by totalScore desc, earliest contributing timestamp as tiebreak. test_taker_id is null for pure-scan entities (no test_takers row).",
    parameters: "(testId: number, options?: { limit?: number })",
    returns: "Array<{ rank, front_id, display_name, entity_type: 'team'|'student', test_taker_id, student_id, team_id, totalScore, problemCount, lastSubmittedAt, scoreBreakdown: { online, scan, manual } }>",
    example: "const top = await api.tests.getLeaderboard(5, { limit: 25 }); return top;",
  },
  {
    name: "api.tests.getProblemStats",
    category: "tests",
    description: "Per-problem stats across all 3 sources. Reports attempted/correct/incorrect/unsure/conflict/ungraded counts plus avgScore. The unsure/conflict/ungraded buckets surface stuck in-person grading.",
    parameters: "(testId: number)",
    returns: "Array<{ test_problem_id, problem_number, page_number, totalPoints, attempted, correct, incorrect, unsure, conflict, ungraded, avgScore }>",
    example: "const stats = await api.tests.getProblemStats(5); return stats;",
  },
  {
    name: "api.tests.getTakerScore",
    category: "tests",
    description: "Per-problem score breakdown for ONE entity, merged across online + scan + manual sources. Look up by front_id (preferred) or test_taker_id. perProblem is keyed by problem_number; each entry says which source produced it (online/scan/manual) and its final state (correct/incorrect/unsure/conflict/ungraded/unanswered). Returns null if the entity didn't participate.",
    parameters: "(testId: number, params: { front_id?: number; test_taker_id?: number })",
    returns: "{ rank, front_id, display_name, entity_type, test_taker_id, student_id, team_id, totalScore, problemCount, lastSubmittedAt, scoreBreakdown, perProblem: Record<problem_number, { test_problem_id, problem_number, source, state, points, answer_latex, lastEditedAt }> } | null",
    example: "const score = await api.tests.getTakerScore(532, { front_id: 17 }); return score;",
  },
  {
    name: "api.tests.getScanGradingProgress",
    category: "tests",
    description: "Per-problem in-person scan grading rollup: how many scans are graded / conflicted / overridden / still ungraded, plus the resolved correct/incorrect/unsure counts. Per (problem, scan) cells with no scan_grades row count as ungraded. Use getScanGradeStats for the legacy flat 3-number summary.",
    parameters: "(testId: number)",
    returns: "Array<{ test_problem_id, problem_number, page_number, totalPoints, scansTotal, graded, conflicts, overridden, ungraded, unsure, correct, incorrect }>",
    example: "const prog = await api.tests.getScanGradingProgress(532); return prog;",
  },
  {
    name: "api.tests.getGutsScoreboard",
    category: "tests",
    description: "Manual-grades (Guts/team) scoreboard. Per-team rows with per-problem status + score, ordered by totalScore desc. Use getLeaderboard for the cross-source unified view; this exposes raw manual_grades fields (status string, answer_latex, graded_at) for direct inspection.",
    parameters: "(testId: number)",
    returns: "Array<{ rank, front_id, team_id, team_name, totalScore, correctCount, lastGradedAt, problems: Record<problem_number, { status, score, answer_latex, graded_at }> }>",
    example: "const guts = await api.tests.getGutsScoreboard(540); return guts;",
  },
  {
    name: "api.tests.getAnswerHistogram",
    category: "tests",
    description: "Frequency of every distinct answer to one problem with correctness. Spot collusion clusters (many takers with the same wrong answer), heavy distractors, off-by-one popular answers. Sorted by count desc.",
    parameters: "(testId: number, problem_number: number)",
    returns: "{ test_problem_id, problem_number, totalAttempts, distinctAnswers, answers: Array<{ answer_latex, count, frequency, correct, pointsEach }> }",
    example: "const hist = await api.tests.getAnswerHistogram(532, 7); return hist;",
  },
  {
    name: "api.tests.getTakerTimeline",
    category: "tests",
    description: "Chronological online-submission timeline for ONE taker. Returns every graded_test_answers edit sorted by last_edited_time, with secondsSincePrev. Forensic tool: bursts, long gaps, end-of-test cramming. Online-only (scan/manual have no per-submission timestamps from the taker).",
    parameters: "(testId: number, params: { front_id?: number; test_taker_id?: number })",
    returns: "{ test_taker_id, front_id, events: Array<{ test_problem_id, problem_number, answer_latex, correct, score, last_edited_time, secondsSincePrev }> } | null",
    example: "const tl = await api.tests.getTakerTimeline(532, { front_id: 17 }); return tl;",
  },
  {
    name: "api.tests.findRapidSubmissions",
    category: "tests",
    description: "Find takers who submitted minAnswers (default 5) within withinSeconds (default 10). Catches bulk-paste, scripted-submit, and last-second answer dumps. Sorted by burst size desc.",
    parameters: "(testId: number, options?: { minAnswers?: number; withinSeconds?: number; onlyIncorrect?: boolean })",
    returns: "Array<{ front_id, display_name, test_taker_id, student_id, team_id, startedAt, endedAt, spanSeconds, answerCount, answersPerSecond, answers: Array<{ problem_number, answer_latex, correct, score, last_edited_time }> }>",
    example: "const bursts = await api.tests.findRapidSubmissions(532, { minAnswers: 8, withinSeconds: 15 }); return bursts;",
  },
  {
    name: "api.tests.findSimilarTakers",
    category: "tests",
    description: "Pairwise overlap of identical answers across all takers on this test. Score = sharedCorrect + 3*sharedIncorrect (matching wrong answers is far more diagnostic than matching right ones). Catches sustained collusion that single-problem collisions miss. Sorted by score desc.",
    parameters: "(testId: number, options?: { minShared?: number; limit?: number; problemNumbers?: number[] })",
    returns: "Array<{ score, sharedTotal, sharedCorrect, sharedIncorrect, takerA, takerB, sharedProblems: Array<{ problem_number, test_problem_id, answer_latex, correct }> }>",
    example: "const pairs = await api.tests.findSimilarTakers(532, { minShared: 5, limit: 25 }); return pairs;",
  },
  {
    name: "api.tests.findAnswers",
    category: "tests",
    description: "Find all takers who submitted an exact answer to a problem. Pass test_problem_id directly, or testId + problem_number. Each result's `taker` includes front_id (user-facing ID) — use that when reporting matches to the user.",
    parameters: "(params: { testId?: number; test_problem_id?: number; problem_number?: number; answer: string; limit?: number })",
    returns: "Array<GradedTestAnswer & { taker: { front_id, taker_name, test_taker_id, student_id, team_id } | null }>",
    example: 'const matches = await api.tests.findAnswers({ testId: 5, problem_number: 7, answer: "42" }); return matches;',
  },
  {
    name: "api.tests.findAnswerCollisions",
    category: "tests",
    description: "Detect groups of takers who submitted the same answer to the same problem. With windowSeconds>0, only groups whose last_edited_time values fit within that sliding window are returned — useful for flagging simultaneous / copied submissions. Default windowSeconds=0 (no time filter). Each taker entry has front_id + display_name; report those to the user, not internal IDs. Sorted by group size desc.",
    parameters: "(testId: number, options?: { windowSeconds?: number; minGroupSize?: number; problemNumbers?: number[]; onlyIncorrect?: boolean })",
    returns: "Array<{ test_problem_id, problem_number, answer_latex, windowSpanSeconds, takers: Array<{ front_id, display_name, test_taker_id, student_id, team_id, last_edited_time, score, correct }> }>",
    example: "const suspicious = await api.tests.findAnswerCollisions(5, { windowSeconds: 30, minGroupSize: 2, onlyIncorrect: true }); return suspicious;",
  },

  // ── analytics ──
  {
    name: "api.analytics.registrationSummary",
    category: "analytics",
    description: "Registration summary: total students, teams, orgs, independent students",
    parameters: "(eventId: number)",
    returns: "{ totalStudents, totalTeams, totalOrgs, independentStudents, studentsWithoutTeam }",
    example: "const summary = await api.analytics.registrationSummary(18); return summary;",
  },
  {
    name: "api.analytics.teamSizeDistribution",
    category: "analytics",
    description: "Distribution of team sizes",
    parameters: "(eventId: number)",
    returns: "Array<{ teamSize: number; count: number }>",
    example: "const dist = await api.analytics.teamSizeDistribution(18); return dist;",
  },
  {
    name: "api.analytics.orgBreakdown",
    category: "analytics",
    description: "Students and teams per organization",
    parameters: "(eventId: number)",
    returns: "Array<{ orgId, orgName, students, teams }>",
    example: "const breakdown = await api.analytics.orgBreakdown(18); return breakdown;",
  },
  {
    name: "api.analytics.ticketSummary",
    category: "analytics",
    description: "Ticket summary: sold, refunded, pending, revenue",
    parameters: "(eventId: number)",
    returns: "{ ticketPriceCents, totalSold, totalRefunded, totalPendingRefund, netTickets, grossRevenueCents, netRevenueCents }",
    example: "const summary = await api.analytics.ticketSummary(18); return summary;",
  },
  {
    name: "api.analytics.gradeSummary",
    category: "analytics",
    description: "Per-test: test takers count, graded answers, average score",
    parameters: "(eventId: number)",
    returns: "Array<{ testId, testName, isTeam, testTakers, gradedAnswers, averageScore }>",
    example: "const grades = await api.analytics.gradeSummary(18); return grades;",
  },
  {
    name: "api.analytics.registrationTimeline",
    category: "analytics",
    description: "Registrations over time with cumulative count",
    parameters: "(eventId: number)",
    returns: "Array<{ date: string; newRegistrations: number; cumulative: number }>",
    example: "const timeline = await api.analytics.registrationTimeline(18); return timeline;",
  },
  {
    name: "api.analytics.studentsWithoutTeam",
    category: "analytics",
    description: "Count of students not assigned to any team",
    parameters: "(eventId: number)",
    returns: "number",
    example: "const count = await api.analytics.studentsWithoutTeam(18); return count;",
  },
  {
    name: "api.analytics.customFieldSummary",
    category: "analytics",
    description: "Aggregate custom field responses with value counts",
    parameters: '(eventId: number, table?: "orgs" | "students" | "teams")',
    returns: "Array<{ fieldId, label, type, totalResponses, valueCounts }>",
    example: "const summary = await api.analytics.customFieldSummary(18); return summary;",
  },
  {
    name: "api.analytics.studentTestMatrix",
    category: "analytics",
    description: "Cross-test score grid for every student across every individual (non-team) test in the event. Every row has front_id (user-facing ID) + name — use those when reporting. Scores are totals; null means the student didn't take that test. Output can be large — .filter/.slice on rows to stay under response limits.",
    parameters: "(eventId: number)",
    returns: "{ tests: Array<{ testId, testName }>, rows: Array<{ front_id, name, team_name, student_id, email, team_id, scores: Record<testName, number | null> }> }",
    example: 'const m = await api.analytics.studentTestMatrix(18); const topAlg = m.rows.slice().sort((a,b)=>(b.scores["Algebra"]||0)-(a.scores["Algebra"]||0)).slice(0,10); return topAlg.map(r => ({ front_id: r.front_id, name: r.name, scores: r.scores }));',
  },
  {
    name: "api.analytics.teamTestMatrix",
    category: "analytics",
    description: "Cross-test score grid for every team across every team test in the event. Every row has front_id (user-facing ID) + team_name — use those when reporting.",
    parameters: "(eventId: number)",
    returns: "{ tests: Array<{ testId, testName }>, rows: Array<{ front_id, team_name, team_id, org_id, org_name, scores: Record<testName, number | null> }> }",
    example: 'const m = await api.analytics.teamTestMatrix(18); return m.rows.filter(r => (r.scores["Guts"]||0) > 200 && (r.scores["Team"]||0) < 50).map(r => ({ front_id: r.front_id, team_name: r.team_name, scores: r.scores }));',
  },

  // ── export ──
  {
    name: "api.export.students",
    category: "export",
    description: "Export student list as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "StudentRow[] | string",
    example: 'const csv = await api.export.students(18, "csv"); return csv;',
  },
  {
    name: "api.export.teams",
    category: "export",
    description: "Export teams with members as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "TeamRow[] | string",
    example: "const teams = await api.export.teams(18); return teams;",
  },
  {
    name: "api.export.orgs",
    category: "export",
    description: "Export organizations as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "OrgRow[] | string",
    example: 'const csv = await api.export.orgs(18, "csv"); return csv;',
  },
  {
    name: "api.export.ticketOrders",
    category: "export",
    description: "Export ticket orders as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "TicketOrderRow[] | string",
    example: "const orders = await api.export.ticketOrders(18); return orders;",
  },
  {
    name: "api.export.refundRequests",
    category: "export",
    description: "Export refund requests as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "RefundRow[] | string",
    example: 'const csv = await api.export.refundRequests(18, "csv"); return csv;',
  },
];

/**
 * Search the API spec for methods matching a query string.
 * Case-insensitive match on name, category, and description.
 * When `readOnly` is true, write methods are excluded from results.
 */
export function searchSpec(
  query: string,
  options: { readOnly?: boolean } = {}
): MethodSpec[] {
  const lower = query.toLowerCase();
  const terms = lower.split(/\s+/).filter(Boolean);

  return API_SPEC.filter((method) => {
    if (options.readOnly && method.write) return false;
    const searchable =
      `${method.name} ${method.category} ${method.description}`.toLowerCase();
    return terms.every((term) => searchable.includes(term));
  });
}

/**
 * The canonical list of write-method paths (e.g. "students.transferToTeam").
 * Derived from API_SPEC so the runtime enforcement and the spec filter share
 * one source of truth. Used to build a read-only wrapper around the api object.
 */
export const WRITE_METHOD_PATHS: ReadonlySet<string> = new Set(
  API_SPEC.filter((m) => m.write).map((m) => m.name.replace(/^api\./, ""))
);
