export interface MethodSpec {
  name: string;
  category: string;
  description: string;
  parameters: string;
  returns: string;
  example: string;
}

export const API_SPEC: MethodSpec[] = [
  // ── events ──
  {
    name: "api.events.list",
    category: "events",
    description: "List configured events (filtered to allowed event IDs)",
    parameters: "()",
    returns: "Event[]",
    example: "const events = await api.events.list(); return events;",
  },
  {
    name: "api.events.get",
    category: "events",
    description: "Get event details with host info",
    parameters: "(eventId: number)",
    returns: "Event & { host: Host }",
    example: "const event = await api.events.get(18); return event;",
  },
  {
    name: "api.events.getTests",
    category: "events",
    description: "Get all tests for an event (admin view, includes hidden)",
    parameters: "(eventId: number)",
    returns: "Test[]",
    example: "const tests = await api.events.getTests(18); return tests;",
  },
  {
    name: "api.events.getOrganizations",
    category: "events",
    description: "Get orgs registered for an event with coaches",
    parameters: "(eventId: number)",
    returns: "Array<OrgEvent & { org: Org & { coaches: OrgCoach[] } }>",
    example: "const orgs = await api.events.getOrganizations(18); return orgs;",
  },
  {
    name: "api.events.getTeams",
    category: "events",
    description: "Get all teams for an event",
    parameters: "(eventId: number)",
    returns: "Team[]",
    example: "const teams = await api.events.getTeams(18); return teams;",
  },
  {
    name: "api.events.getStudents",
    category: "events",
    description: "Get all students registered for an event",
    parameters: "(eventId: number)",
    returns: "StudentEvent[]",
    example: "const students = await api.events.getStudents(18); return students;",
  },
  {
    name: "api.events.getIndependentTeams",
    category: "events",
    description: "Get teams not in any organization",
    parameters: "(eventId: number)",
    returns: "Team[]",
    example: "const teams = await api.events.getIndependentTeams(18); return teams;",
  },
  {
    name: "api.events.getTicketCount",
    category: "events",
    description: "Get total tickets sold for an event",
    parameters: "(eventId: number)",
    returns: "number",
    example: "const count = await api.events.getTicketCount(18); return count;",
  },
  {
    name: "api.events.getCustomFields",
    category: "events",
    description: "Get custom fields for an event",
    parameters: '(eventId: number, table?: "orgs" | "students" | "teams")',
    returns: "CustomField[]",
    example: 'const fields = await api.events.getCustomFields(18, "students"); return fields;',
  },

  // ── students ──
  {
    name: "api.students.list",
    category: "students",
    description: "List students for an event with optional pagination",
    parameters: "(eventId: number, options?: { limit?: number; offset?: number; withDetails?: boolean })",
    returns: "StudentEvent[]",
    example: "const students = await api.students.list(18, { limit: 20 }); return students;",
  },
  {
    name: "api.students.get",
    category: "students",
    description: "Get student event details (team, org, waiver)",
    parameters: "(studentId: string, eventId: number)",
    returns: "StudentEvent | null",
    example: 'const se = await api.students.get("abc-123", 18); return se;',
  },
  {
    name: "api.students.search",
    category: "students",
    description: "Search students by name, email, or front_id",
    parameters: "(params: { eventId: number; name?: string; email?: string; frontId?: number })",
    returns: "StudentEvent[]",
    example: 'const results = await api.students.search({ eventId: 18, name: "John" }); return results;',
  },
  {
    name: "api.students.getWithoutTeam",
    category: "students",
    description: "Get students not assigned to any team",
    parameters: "(eventId: number)",
    returns: "StudentEvent[]",
    example: "const unassigned = await api.students.getWithoutTeam(18); return unassigned;",
  },
  {
    name: "api.students.getTicketOrder",
    category: "students",
    description: "Get student's ticket order with refund status",
    parameters: "(studentId: string, eventId: number)",
    returns: "TicketOrder | null",
    example: 'const order = await api.students.getTicketOrder("abc-123", 18); return order;',
  },
  {
    name: "api.students.getAvailableTickets",
    category: "students",
    description: "Get net available tickets for a student",
    parameters: "(studentId: string, eventId: number)",
    returns: "number",
    example: 'const available = await api.students.getAvailableTickets("abc-123", 18); return available;',
  },
  {
    name: "api.students.transferToTeam",
    category: "students",
    description: "Move student to a team (use -1 to remove from team)",
    parameters: "(studentEventId: number, teamId: number)",
    returns: "StudentEvent",
    example: "const result = await api.students.transferToTeam(42, 7); return result;",
  },
  {
    name: "api.students.transferToOrg",
    category: "students",
    description: "Move student to an org (removes team, use -1 to remove org)",
    parameters: "(studentEventId: number, orgId: number)",
    returns: "StudentEvent",
    example: "const result = await api.students.transferToOrg(42, 5); return result;",
  },
  {
    name: "api.students.removeFromTeam",
    category: "students",
    description: "Remove student from team (keep event registration)",
    parameters: "(studentEventId: number)",
    returns: "StudentEvent",
    example: "const result = await api.students.removeFromTeam(42); return result;",
  },
  {
    name: "api.students.removeFromEvent",
    category: "students",
    description: "Delete student registration from event entirely",
    parameters: "(studentEventId: number)",
    returns: "{ success: boolean }",
    example: "const result = await api.students.removeFromEvent(42); return result;",
  },

  // ── teams ──
  {
    name: "api.teams.list",
    category: "teams",
    description: "List all teams for an event",
    parameters: "(eventId: number)",
    returns: "Team[]",
    example: "const teams = await api.teams.list(18); return teams;",
  },
  {
    name: "api.teams.get",
    category: "teams",
    description: "Get team details with members",
    parameters: "(teamId: number)",
    returns: "Team & { members: StudentEvent[] }",
    example: "const team = await api.teams.get(7); return team;",
  },
  {
    name: "api.teams.search",
    category: "teams",
    description: "Search teams by name or join code",
    parameters: "(eventId: number, params: { name?: string; joinCode?: string })",
    returns: "Team[]",
    example: 'const teams = await api.teams.search(18, { name: "Alpha" }); return teams;',
  },
  {
    name: "api.teams.getMembers",
    category: "teams",
    description: "Get team members",
    parameters: "(teamId: number)",
    returns: "StudentEvent[]",
    example: "const members = await api.teams.getMembers(7); return members;",
  },
  {
    name: "api.teams.getAvailableTickets",
    category: "teams",
    description: "Get team ticket pool (total - refunds) and used count",
    parameters: "(teamId: number, eventId: number)",
    returns: "{ pool: number; used: number }",
    example: "const tickets = await api.teams.getAvailableTickets(7, 18); return tickets;",
  },
  {
    name: "api.teams.transferToOrg",
    category: "teams",
    description: "Transfer team to organization (uses RPC, -1 to remove org)",
    parameters: "(teamId: number, orgId: number)",
    returns: "{ team: Team; students: StudentEvent[] }",
    example: "const result = await api.teams.transferToOrg(7, 5); return result;",
  },
  {
    name: "api.teams.create",
    category: "teams",
    description: "Create a new team for an event",
    parameters: "(eventId: number, teamData: { team_name?: string; org_id?: number })",
    returns: "Team",
    example: 'const team = await api.teams.create(18, { team_name: "Team Alpha" }); return team;',
  },
  {
    name: "api.teams.update",
    category: "teams",
    description: "Update team name",
    parameters: "(teamId: number, data: { team_name?: string })",
    returns: "Team",
    example: 'const team = await api.teams.update(7, { team_name: "New Name" }); return team;',
  },
  {
    name: "api.teams.delete",
    category: "teams",
    description: "Delete team (optionally delete students too)",
    parameters: "(teamId: number, deleteStudents?: boolean)",
    returns: "{ success: boolean; affectedStudents: number; deletedStudents: number }",
    example: "const result = await api.teams.delete(7); return result;",
  },

  // ── orgs ──
  {
    name: "api.orgs.list",
    category: "orgs",
    description: "List all orgs registered for an event with coaches",
    parameters: "(eventId: number)",
    returns: "Array<OrgEvent & { org: Org & { coaches: OrgCoach[] } }>",
    example: "const orgs = await api.orgs.list(18); return orgs;",
  },
  {
    name: "api.orgs.get",
    category: "orgs",
    description: "Get org details with coaches",
    parameters: "(orgId: number)",
    returns: "Org & { coaches: OrgCoach[] }",
    example: "const org = await api.orgs.get(5); return org;",
  },
  {
    name: "api.orgs.getDetails",
    category: "orgs",
    description: "Full org details: coaches, teams with members, event registration",
    parameters: "(orgId: number, eventId: number)",
    returns: "Org & { coaches, teams, orgEvent }",
    example: "const detail = await api.orgs.getDetails(5, 18); return detail;",
  },
  {
    name: "api.orgs.getTeams",
    category: "orgs",
    description: "Get org's teams with members for an event",
    parameters: "(orgId: number, eventId: number)",
    returns: "Array<Team & { members: StudentEvent[] }>",
    example: "const teams = await api.orgs.getTeams(5, 18); return teams;",
  },
  {
    name: "api.orgs.getTicketCount",
    category: "orgs",
    description: "Get net available tickets for an org (tickets - refunds)",
    parameters: "(eventId: number, orgId: number)",
    returns: "number",
    example: "const count = await api.orgs.getTicketCount(18, 5); return count;",
  },
  {
    name: "api.orgs.getTicketOrders",
    category: "orgs",
    description: "Get all ticket orders and refund requests for an org",
    parameters: "(orgId: number, eventId: number)",
    returns: "TicketOrder[]",
    example: "const orders = await api.orgs.getTicketOrders(5, 18); return orders;",
  },
  {
    name: "api.orgs.removeStudent",
    category: "orgs",
    description: "Remove student from org (clears org_id and team_id)",
    parameters: "(studentEventId: number)",
    returns: "StudentEvent",
    example: "const result = await api.orgs.removeStudent(42); return result;",
  },

  // ── tickets ──
  {
    name: "api.tickets.listOrders",
    category: "tickets",
    description: "List all ticket orders for an event",
    parameters: "(eventId: number)",
    returns: "TicketOrder[]",
    example: "const orders = await api.tickets.listOrders(18); return orders;",
  },
  {
    name: "api.tickets.getOrder",
    category: "tickets",
    description: "Get a specific ticket order with refund requests",
    parameters: "(ticketId: number)",
    returns: "TicketOrder",
    example: "const order = await api.tickets.getOrder(42); return order;",
  },
  {
    name: "api.tickets.listRefundRequests",
    category: "tickets",
    description: "List refund requests for an event, optionally filtered by status",
    parameters: '(eventId: number, status?: "PENDING" | "APPROVED" | "DENIED")',
    returns: "RefundRequest[]",
    example: 'const pending = await api.tickets.listRefundRequests(18, "PENDING"); return pending;',
  },
  {
    name: "api.tickets.getRefundRequest",
    category: "tickets",
    description: "Get a specific refund request with ticket details",
    parameters: "(refundId: number)",
    returns: "RefundRequest & { ticket: TicketOrder }",
    example: "const refund = await api.tickets.getRefundRequest(10); return refund;",
  },
  {
    name: "api.tickets.approveRefund",
    category: "tickets",
    description: "Approve a pending refund in the database. WARNING: This does NOT process the actual payment refund. The admin must still manually refund via Stripe/Eventbrite/Humanitix dashboard. Always inform the user of this when reporting the result.",
    parameters: "(refundId: number, quantity: number, responseMessage?: string)",
    returns: "RefundRequest & { _warning: string }",
    example: 'const result = await api.tickets.approveRefund(10, 2, "Approved"); return result;',
  },
  {
    name: "api.tickets.denyRefund",
    category: "tickets",
    description: "Deny a pending refund request",
    parameters: "(refundId: number, responseMessage?: string)",
    returns: "RefundRequest",
    example: 'const result = await api.tickets.denyRefund(10, "Event is non-refundable"); return result;',
  },
  {
    name: "api.tickets.getEventRevenue",
    category: "tickets",
    description: "Calculate total revenue: gross, refunded, net",
    parameters: "(eventId: number)",
    returns: "{ ticketPriceCents, totalSold, totalRefunded, netTickets, grossRevenueCents, refundedCents, netRevenueCents }",
    example: "const revenue = await api.tickets.getEventRevenue(18); return revenue;",
  },

  // ── tests ──
  {
    name: "api.tests.list",
    category: "tests",
    description: "List all tests for an event",
    parameters: "(eventId: number)",
    returns: "Test[]",
    example: "const tests = await api.tests.list(18); return tests;",
  },
  {
    name: "api.tests.get",
    category: "tests",
    description: "Get test details (from detailed view)",
    parameters: "(testId: number)",
    returns: "Test (detailed)",
    example: "const test = await api.tests.get(5); return test;",
  },
  {
    name: "api.tests.getProblems",
    category: "tests",
    description: "Get test problems ordered by problem number",
    parameters: "(testId: number)",
    returns: "TestProblem[]",
    example: "const problems = await api.tests.getProblems(5); return problems;",
  },
  {
    name: "api.tests.getTestTakers",
    category: "tests",
    description: "Get test takers with details (enriched with front_id for individuals)",
    parameters: "(testId: number)",
    returns: "TestTaker[]",
    example: "const takers = await api.tests.getTestTakers(5); return takers;",
  },
  {
    name: "api.tests.getResults",
    category: "tests",
    description: "Get graded test answers",
    parameters: "(testId: number)",
    returns: "GradedTestAnswer[]",
    example: "const results = await api.tests.getResults(5); return results;",
  },
  {
    name: "api.tests.getScanGradeStats",
    category: "tests",
    description: "Get scan grading progress: total, graded, conflicts",
    parameters: "(testId: number)",
    returns: "{ totalProblems: number; gradedProblems: number; conflictProblems: number }",
    example: "const stats = await api.tests.getScanGradeStats(5); return stats;",
  },

  // ── analytics ──
  {
    name: "api.analytics.registrationSummary",
    category: "analytics",
    description: "Registration summary: total students, teams, orgs, independent students",
    parameters: "(eventId: number)",
    returns: "{ totalStudents, totalTeams, totalOrgs, independentStudents, studentsWithoutTeam }",
    example: "const summary = await api.analytics.registrationSummary(18); return summary;",
  },
  {
    name: "api.analytics.teamSizeDistribution",
    category: "analytics",
    description: "Distribution of team sizes",
    parameters: "(eventId: number)",
    returns: "Array<{ teamSize: number; count: number }>",
    example: "const dist = await api.analytics.teamSizeDistribution(18); return dist;",
  },
  {
    name: "api.analytics.orgBreakdown",
    category: "analytics",
    description: "Students and teams per organization",
    parameters: "(eventId: number)",
    returns: "Array<{ orgId, orgName, students, teams }>",
    example: "const breakdown = await api.analytics.orgBreakdown(18); return breakdown;",
  },
  {
    name: "api.analytics.ticketSummary",
    category: "analytics",
    description: "Ticket summary: sold, refunded, pending, revenue",
    parameters: "(eventId: number)",
    returns: "{ ticketPriceCents, totalSold, totalRefunded, totalPendingRefund, netTickets, grossRevenueCents, netRevenueCents }",
    example: "const summary = await api.analytics.ticketSummary(18); return summary;",
  },
  {
    name: "api.analytics.gradeSummary",
    category: "analytics",
    description: "Per-test: test takers count, graded answers, average score",
    parameters: "(eventId: number)",
    returns: "Array<{ testId, testName, isTeam, testTakers, gradedAnswers, averageScore }>",
    example: "const grades = await api.analytics.gradeSummary(18); return grades;",
  },
  {
    name: "api.analytics.registrationTimeline",
    category: "analytics",
    description: "Registrations over time with cumulative count",
    parameters: "(eventId: number)",
    returns: "Array<{ date: string; newRegistrations: number; cumulative: number }>",
    example: "const timeline = await api.analytics.registrationTimeline(18); return timeline;",
  },
  {
    name: "api.analytics.studentsWithoutTeam",
    category: "analytics",
    description: "Count of students not assigned to any team",
    parameters: "(eventId: number)",
    returns: "number",
    example: "const count = await api.analytics.studentsWithoutTeam(18); return count;",
  },
  {
    name: "api.analytics.customFieldSummary",
    category: "analytics",
    description: "Aggregate custom field responses with value counts",
    parameters: '(eventId: number, table?: "orgs" | "students" | "teams")',
    returns: "Array<{ fieldId, label, type, totalResponses, valueCounts }>",
    example: "const summary = await api.analytics.customFieldSummary(18); return summary;",
  },

  // ── export ──
  {
    name: "api.export.students",
    category: "export",
    description: "Export student list as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "StudentRow[] | string",
    example: 'const csv = await api.export.students(18, "csv"); return csv;',
  },
  {
    name: "api.export.teams",
    category: "export",
    description: "Export teams with members as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "TeamRow[] | string",
    example: "const teams = await api.export.teams(18); return teams;",
  },
  {
    name: "api.export.orgs",
    category: "export",
    description: "Export organizations as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "OrgRow[] | string",
    example: 'const csv = await api.export.orgs(18, "csv"); return csv;',
  },
  {
    name: "api.export.ticketOrders",
    category: "export",
    description: "Export ticket orders as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "TicketOrderRow[] | string",
    example: "const orders = await api.export.ticketOrders(18); return orders;",
  },
  {
    name: "api.export.refundRequests",
    category: "export",
    description: "Export refund requests as JSON or CSV",
    parameters: '(eventId: number, format?: "json" | "csv")',
    returns: "RefundRow[] | string",
    example: 'const csv = await api.export.refundRequests(18, "csv"); return csv;',
  },
];

/**
 * Search the API spec for methods matching a query string.
 * Case-insensitive match on name, category, and description.
 */
export function searchSpec(query: string): MethodSpec[] {
  const lower = query.toLowerCase();
  const terms = lower.split(/\s+/).filter(Boolean);

  return API_SPEC.filter((method) => {
    const searchable =
      `${method.name} ${method.category} ${method.description}`.toLowerCase();
    return terms.every((term) => searchable.includes(term));
  });
}
